// 18 Boston-area public golf courses with GolfNow facility IDs
// GolfNow slugs verified from golfnow.com/facilities/... URLs

export const BOSTON_COURSES = [
  {
    name: 'Fresh Pond Golf Course',
    slug: 'fresh-pond',
    address: '691 Huron Ave, Cambridge, MA 02138',
    city: 'Cambridge',
    lat: 42.3814,
    lng: -71.1497,
    phone: '(617) 349-6282',
    website: 'https://www.cambridgema.gov/golf',
    golfnow_facility_id: '4506',
    golfnow_slug: 'fresh-pond-golf-course',
    holes_available: [9, 18],
    walking_allowed: true,
    price_range: '$',
    price_min: 18,
    price_max: 32,
    description: '9-hole municipal course in Cambridge. One of the most accessible public courses near the city.',
  },
  {
    name: 'William J. Devine Golf Course',
    slug: 'william-devine',
    address: '1 Circuit Dr, Boston, MA 02121',
    city: 'Boston',
    lat: 42.3022,
    lng: -71.1011,
    phone: '(617) 265-4084',
    website: 'https://www.boston.gov/departments/parks-and-recreation/golf',
    golfnow_facility_id: '4510',
    golfnow_slug: 'william-j-devine-golf-course-at-franklin-park',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$',
    price_min: 30,
    price_max: 46,
    description: '18-hole municipal course in Franklin Park, Boston. Designed by Donald Ross, one of the oldest public courses in the US.',
  },
  {
    name: 'George Wright Golf Course',
    slug: 'george-wright',
    address: '420 West St, Hyde Park, MA 02136',
    city: 'Boston',
    lat: 42.2519,
    lng: -71.1264,
    phone: '(617) 361-8313',
    website: 'https://www.boston.gov/departments/parks-and-recreation/golf',
    golfnow_facility_id: '4509',
    golfnow_slug: 'george-wright-golf-course',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$',
    price_min: 30,
    price_max: 46,
    description: '18-hole municipal course in Hyde Park. Another Donald Ross design operated by the City of Boston.',
  },
  {
    name: 'Ponkapoag Golf Course (Course 1)',
    slug: 'ponkapoag-1',
    address: '2167 Washington St, Canton, MA 02021',
    city: 'Canton',
    lat: 42.1714,
    lng: -71.1075,
    phone: '(781) 828-4242',
    website: 'https://www.mdcr.mass.gov/programs/golf/ponkapoag',
    golfnow_facility_id: '4511',
    golfnow_slug: 'ponkapoag-golf-course-course-1',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$',
    price_min: 30,
    price_max: 42,
    description: 'State-operated 18-hole course in the Blue Hills Reservation. Great wooded setting.',
  },
  {
    name: 'Ponkapoag Golf Course (Course 2)',
    slug: 'ponkapoag-2',
    address: '2167 Washington St, Canton, MA 02021',
    city: 'Canton',
    lat: 42.1703,
    lng: -71.1080,
    phone: '(781) 828-4242',
    website: 'https://www.mdcr.mass.gov/programs/golf/ponkapoag',
    golfnow_facility_id: '4512',
    golfnow_slug: 'ponkapoag-golf-course-course-2',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$',
    price_min: 28,
    price_max: 40,
    description: 'Second 18-hole course at the Ponkapoag complex. More open layout than Course 1.',
  },
  {
    name: 'Putterham Meadows Golf Club',
    slug: 'putterham-meadows',
    address: '1281 W Roxbury Pkwy, Chestnut Hill, MA 02467',
    city: 'Chestnut Hill',
    lat: 42.3200,
    lng: -71.1620,
    phone: '(617) 730-2078',
    website: 'https://www.brooklinema.gov/golf',
    golfnow_facility_id: '4513',
    golfnow_slug: 'brookline-golf-club-at-putterham',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 40,
    price_max: 58,
    description: '18-hole municipal course operated by Brookline. Well-maintained with tree-lined fairways.',
  },
  {
    name: 'Granite Links Golf Club',
    slug: 'granite-links',
    address: '100 Quarry Hills Dr, Quincy, MA 02169',
    city: 'Quincy',
    lat: 42.2532,
    lng: -71.0228,
    phone: '(617) 689-1900',
    website: 'https://www.granitelinks.com',
    golfnow_facility_id: '6843',
    golfnow_slug: 'granite-links-golf-club-at-quarry-hills',
    holes_available: [18],
    walking_allowed: false,
    price_range: '$$$',
    price_min: 65,
    price_max: 115,
    description: 'Top-rated 18-hole course in Quincy with stunning Boston skyline views. Cart required on most rounds.',
  },
  {
    name: "President's Golf Course",
    slug: 'presidents',
    address: '357 W Squantum St, Quincy, MA 02171',
    city: 'Quincy',
    lat: 42.2769,
    lng: -71.0106,
    phone: '(617) 328-3444',
    website: null,
    golfnow_facility_id: '4514',
    golfnow_slug: 'presidents-golf-course',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 35,
    price_max: 52,
    description: '18-hole public course in Quincy with harbor views.',
  },
  {
    name: 'Furnace Brook Golf Club',
    slug: 'furnace-brook',
    address: '284 Warren St, Wollaston, MA 02170',
    city: 'Wollaston',
    lat: 42.2633,
    lng: -71.0044,
    phone: '(617) 472-2200',
    website: 'https://www.furnacebrookgolf.com',
    golfnow_facility_id: '4515',
    golfnow_slug: 'furnace-brook-golf-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 38,
    price_max: 55,
    description: '18-hole semi-private course in Wollaston. Challenging layout with water features.',
  },
  {
    name: 'Braintree Municipal Golf Course',
    slug: 'braintree-municipal',
    address: '101 Jefferson St, Braintree, MA 02184',
    city: 'Braintree',
    lat: 42.2099,
    lng: -71.0017,
    phone: '(781) 843-6513',
    website: null,
    golfnow_facility_id: '4516',
    golfnow_slug: 'braintree-municipal-golf-course',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$',
    price_min: 28,
    price_max: 40,
    description: 'Affordable 18-hole municipal course south of Boston.',
  },
  {
    name: "Widow's Walk Golf Course",
    slug: 'widows-walk',
    address: '250 The Driftway, Scituate, MA 02066',
    city: 'Scituate',
    lat: 42.1882,
    lng: -70.7449,
    phone: '(781) 544-7777',
    website: 'https://www.widowswalkgolf.com',
    golfnow_facility_id: '4518',
    golfnow_slug: 'widows-walk-golf-course',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 42,
    price_max: 65,
    description: 'Award-winning 18-hole public course on the South Shore. Often ranked best public course in Massachusetts.',
  },
  {
    name: 'Juniper Hill Golf Course',
    slug: 'juniper-hill',
    address: '202 Brigham St, Northborough, MA 01532',
    city: 'Northborough',
    lat: 42.3191,
    lng: -71.6437,
    phone: '(508) 393-2444',
    website: 'https://www.juniperhillgolf.com',
    golfnow_facility_id: '4519',
    golfnow_slug: 'juniper-hill-golf-course',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 38,
    price_max: 55,
    description: 'Two 18-hole courses (Lakeside & Riverside) west of Boston. Great value.',
  },
  {
    name: 'Pinecrest Golf Club',
    slug: 'pinecrest',
    address: '256 Pinecrest Dr, Holliston, MA 01746',
    city: 'Holliston',
    lat: 42.2047,
    lng: -71.4249,
    phone: '(508) 429-9871',
    website: 'https://www.pinecrestgolfclub.com',
    golfnow_facility_id: '4520',
    golfnow_slug: 'pinecrest-golf-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 35,
    price_max: 52,
    description: '18-hole public course with a classic New England layout.',
  },
  {
    name: 'Maplegate Country Club',
    slug: 'maplegate',
    address: '160 Maple St, Bellingham, MA 02019',
    city: 'Bellingham',
    lat: 42.0882,
    lng: -71.4740,
    phone: '(508) 966-4040',
    website: 'https://www.maplegatecc.com',
    golfnow_facility_id: '4521',
    golfnow_slug: 'maplegate-country-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 40,
    price_max: 60,
    description: 'Semi-private 18-hole course with open public tee times. Well-manicured fairways.',
  },
  {
    name: 'Butter Brook Golf Club',
    slug: 'butter-brook',
    address: '157 Goldsmith St, Westford, MA 01886',
    city: 'Westford',
    lat: 42.5800,
    lng: -71.4452,
    phone: '(978) 692-6560',
    website: 'https://www.butterbrookgolf.com',
    golfnow_facility_id: '4522',
    golfnow_slug: 'butter-brook-golf-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 38,
    price_max: 58,
    description: '18-hole public course northwest of Boston. Great condition for the price.',
  },
  {
    name: 'Easton Country Club',
    slug: 'easton-cc',
    address: '265 Purchase St, South Easton, MA 02375',
    city: 'South Easton',
    lat: 42.0315,
    lng: -71.1174,
    phone: '(508) 238-2500',
    website: 'https://www.eastoncountryclub.com',
    golfnow_facility_id: '4523',
    golfnow_slug: 'easton-country-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 40,
    price_max: 60,
    description: 'Public 18-hole course south of Boston with a traditional New England feel.',
  },
  {
    name: 'New England Country Club',
    slug: 'new-england-cc',
    address: '180 Paine St, Bellingham, MA 02019',
    city: 'Bellingham',
    lat: 42.0775,
    lng: -71.4829,
    phone: '(508) 883-2300',
    website: 'https://www.newenglandcountryclub.com',
    golfnow_facility_id: '4524',
    golfnow_slug: 'new-england-country-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$$',
    price_min: 55,
    price_max: 85,
    description: 'Beautiful 18-hole public course with championship-caliber conditions.',
  },
  {
    name: 'Foxborough Country Club',
    slug: 'foxborough-cc',
    address: '33 Walnut St, Foxborough, MA 02035',
    city: 'Foxborough',
    lat: 42.0668,
    lng: -71.2446,
    phone: '(508) 543-4661',
    website: 'https://www.foxboroughcountryclub.com',
    golfnow_facility_id: '4525',
    golfnow_slug: 'foxborough-country-club',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$',
    price_min: 42,
    price_max: 62,
    description: '18-hole public course near Gillette Stadium. Challenging layout with elevation changes.',
  },
]
