// Quality tiers: 'municipal' | 'public' | 'semi_private' | 'premier'
// Characteristics drive fuzzy/vibes queries from the AI

export const BOSTON_COURSES = [
  {
    name: 'Fresh Pond Golf Course',
    slug: 'fresh-pond',
    address: '691 Huron Ave, Cambridge, MA 02138',
    city: 'Cambridge',
    lat: 42.3814, lng: -71.1497,
    phone: '(617) 349-6282',
    website: 'https://freshpondgolf.com/policies/tee-times/',
    golfnow_facility_id: '13095',
    golfnow_slug: 'fresh-pond-golf-course',
    booking_provider: 'webtrac',
    booking_capability: 'deep_link_to_date',
    booking_notes: 'Verified in browser: Cambridge WebTrac tee-time search shows Fresh Pond rows with date/time/player filters.',
    holes_available: [9, 18],
    walking_allowed: true,
    price_range: '$', price_min: 18, price_max: 32,
    quality_tier: 'municipal',
    characteristics: ['beginner_friendly', 'quick_round', 'urban', 'affordable'],
    description: '9-hole municipal course in Cambridge, steps from Harvard. Most accessible public course in the city. Perfect for a quick round or beginners.',
  },
  {
    name: 'William J. Devine Golf Course',
    slug: 'william-devine',
    address: '1 Circuit Dr, Boston, MA 02121',
    city: 'Boston',
    lat: 42.3022, lng: -71.1011,
    phone: '(617) 265-4084',
    website: 'https://cityofbostongolf.com/non-permit-holder-tee-times/',
    golfnow_facility_id: '4510',
    golfnow_slug: 'william-j-devine-golf-course-at-franklin-park',
    booking_provider: 'cps',
    booking_capability: 'blocked_in_headless',
    booking_notes: 'CPS booking surface is bot-sensitive in headless browser; use normal browser handoff.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$', price_min: 30, price_max: 46,
    quality_tier: 'municipal',
    characteristics: ['historic', 'donald_ross', 'wooded', 'challenging', 'affordable'],
    description: 'Donald Ross-designed 18-hole course in Franklin Park — one of the oldest public courses in the US (1896). Historic, wooded, and genuinely challenging for the price.',
  },
  {
    name: 'George Wright Golf Course',
    slug: 'george-wright',
    address: '420 West St, Hyde Park, MA 02136',
    city: 'Boston',
    lat: 42.2519, lng: -71.1264,
    phone: '(617) 361-8313',
    website: 'https://cityofbostongolf.com/non-permit-holder-tee-times/',
    golfnow_facility_id: '4509',
    golfnow_slug: 'george-wright-golf-course',
    booking_provider: 'cps',
    booking_capability: 'blocked_in_headless',
    booking_notes: 'CPS booking surface is bot-sensitive in headless browser; use normal browser handoff.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$', price_min: 30, price_max: 46,
    quality_tier: 'municipal',
    characteristics: ['historic', 'donald_ross', 'wooded', 'challenging', 'affordable'],
    description: 'Second Donald Ross-designed municipal course in Boston. Well-maintained with tree-lined fairways. Great value for a proper 18-hole round.',
  },
  {
    name: 'Ponkapoag Golf Course (Course 1)',
    slug: 'ponkapoag-1',
    address: '2167 Washington St, Canton, MA 02021',
    city: 'Canton',
    lat: 42.1714, lng: -71.1075,
    phone: '(781) 828-4242',
    website: 'https://www.mass.gov/locations/ponkapoag-golf-course',
    golfnow_facility_id: '4511',
    golfnow_slug: 'ponkapoag-golf-course-course-1',
    booking_provider: 'course_direct',
    booking_capability: 'course_policy_page',
    booking_notes: 'State course information page; online booking flow requires manual verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$', price_min: 30, price_max: 42,
    quality_tier: 'municipal',
    characteristics: ['scenic', 'wooded', 'nature', 'affordable', 'state_park'],
    description: 'State-operated 18-hole course inside the Blue Hills Reservation. Beautiful wooded setting surrounded by nature. Unique for Boston — feels like you left the city.',
  },
  {
    name: 'Ponkapoag Golf Course (Course 2)',
    slug: 'ponkapoag-2',
    address: '2167 Washington St, Canton, MA 02021',
    city: 'Canton',
    lat: 42.1703, lng: -71.1080,
    phone: '(781) 828-4242',
    website: 'https://www.mass.gov/locations/ponkapoag-golf-course',
    golfnow_facility_id: '4512',
    golfnow_slug: 'ponkapoag-golf-course-course-2',
    booking_provider: 'course_direct',
    booking_capability: 'course_policy_page',
    booking_notes: 'State course information page; online booking flow requires manual verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$', price_min: 28, price_max: 40,
    quality_tier: 'municipal',
    characteristics: ['affordable', 'open_layout', 'state_park', 'beginner_friendly'],
    description: 'Second 18-hole course at Ponkapoag — more open layout, slightly cheaper. Ideal for beginners or when Course 1 is busy.',
  },
  {
    name: 'Putterham Meadows Golf Club',
    slug: 'putterham-meadows',
    address: '1281 W Roxbury Pkwy, Chestnut Hill, MA 02467',
    city: 'Chestnut Hill',
    lat: 42.3200, lng: -71.1620,
    phone: '(617) 730-2078',
    website: 'https://www.brooklinegolf.com',
    golfnow_facility_id: '4513',
    golfnow_slug: 'brookline-golf-club-at-putterham',
    booking_provider: 'foreup',
    booking_capability: 'blocked_in_headless',
    booking_notes: 'foreUP booking URL is exposed from official site but returned 403 in headless eval.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 40, price_max: 58,
    quality_tier: 'public',
    characteristics: ['well_maintained', 'wooded', 'suburban', 'good_conditions'],
    description: 'Well-maintained 18-hole Brookline municipal course with tree-lined fairways. A step up from the city munis in conditioning and layout. Strong value in the $40–58 range.',
  },
  {
    name: 'Granite Links Golf Club',
    slug: 'granite-links',
    address: '100 Quarry Hills Dr, Quincy, MA 02169',
    city: 'Quincy',
    lat: 42.2532, lng: -71.0228,
    phone: '(617) 689-1900',
    website: 'https://www.granitelinks.com/reserve-a-tee-time',
    golfnow_facility_id: '6843',
    golfnow_slug: 'granite-links-golf-club-at-quarry-hills',
    booking_provider: 'northstar',
    booking_capability: 'blocked_in_headless',
    booking_notes: 'Official reserve-a-tee-time page embeds Northstar booking; bot-sensitive in automated browser eval.',
    holes_available: [18],
    walking_allowed: false,
    price_range: '$$$', price_min: 65, price_max: 115,
    quality_tier: 'premier',
    characteristics: ['scenic', 'skyline_views', 'high_quality', 'upscale', 'special_occasion'],
    description: 'Premier 18-hole course in Quincy with stunning Boston skyline views from the fairways. Best-quality public course in the area. Cart required. Worth it for a special round.',
  },
  {
    name: "President's Golf Course",
    slug: 'presidents',
    address: '357 W Squantum St, Quincy, MA 02171',
    city: 'Quincy',
    lat: 42.2769, lng: -71.0106,
    phone: '(617) 328-3444',
    website: 'https://www.presidentsgc.org',
    golfnow_facility_id: '4514',
    golfnow_slug: 'presidents-golf-course',
    booking_provider: 'teeitup',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'Tee It Up booking engine supports course/date routing.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 35, price_max: 52,
    quality_tier: 'public',
    characteristics: ['harbour_views', 'scenic', 'coastal'],
    description: '18-hole public course in Quincy with partial harbor views. Solid mid-range option on the South Shore.',
  },
  {
    name: 'Furnace Brook Golf Club',
    slug: 'furnace-brook',
    address: '284 Warren St, Wollaston, MA 02170',
    city: 'Wollaston',
    lat: 42.2633, lng: -71.0044,
    phone: '(617) 472-2200',
    website: 'https://www.furnacebrookgolf.com',
    golfnow_facility_id: '4515',
    golfnow_slug: 'furnace-brook-golf-club',
    booking_provider: 'foreup',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'foreUP booking engine landing; exact-date behavior needs browser verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 38, price_max: 55,
    quality_tier: 'semi_private',
    characteristics: ['well_maintained', 'challenging', 'water_features'],
    description: 'Semi-private 18-hole course with water features and a more challenging layout. Good conditions. Open to public.',
  },
  {
    name: 'Braintree Municipal Golf Course',
    slug: 'braintree-municipal',
    address: '101 Jefferson St, Braintree, MA 02184',
    city: 'Braintree',
    lat: 42.2099, lng: -71.0017,
    phone: '(781) 843-6513',
    website: 'https://www.braintreegolf.com',
    golfnow_facility_id: '4516',
    golfnow_slug: 'braintree-municipal-golf-course',
    booking_provider: 'course_direct',
    booking_capability: 'manual_date_selection',
    booking_notes: 'Course booking page; user may need to select date/time manually.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$', price_min: 28, price_max: 40,
    quality_tier: 'municipal',
    characteristics: ['affordable', 'no_frills', 'beginner_friendly'],
    description: 'Affordable 18-hole municipal course south of Boston. No-frills but functional. Best for value-first players.',
  },
  {
    name: "Widow's Walk Golf Course",
    slug: 'widows-walk',
    address: '250 The Driftway, Scituate, MA 02066',
    city: 'Scituate',
    lat: 42.1882, lng: -70.7449,
    phone: '(781) 544-7777',
    website: 'https://www.widowswalkgolf.com',
    golfnow_facility_id: '4518',
    golfnow_slug: 'widows-walk-golf-course',
    booking_provider: 'foreup',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'foreUP booking engine landing; exact-date behavior needs browser verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 42, price_max: 65,
    quality_tier: 'public',
    characteristics: ['scenic', 'coastal', 'high_quality', 'well_maintained', 'top_rated'],
    description: "Consistently ranked the best public course in Massachusetts. Scenic coastal setting in Scituate, excellent conditions. Worth the drive south.",
  },
  {
    name: 'Juniper Hill Golf Course',
    slug: 'juniper-hill',
    address: '202 Brigham St, Northborough, MA 01532',
    city: 'Northborough',
    lat: 42.3191, lng: -71.6437,
    phone: '(508) 393-2444',
    website: 'https://www.juniperhillgc.com',
    golfnow_facility_id: '4519',
    golfnow_slug: 'juniper-hill-golf-course',
    booking_provider: 'cps',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'CPS booking engine landing; may be bot-sensitive in automated browsers.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 38, price_max: 55,
    quality_tier: 'public',
    characteristics: ['two_courses', 'good_value', 'well_maintained'],
    description: 'Two 18-hole courses (Lakeside & Riverside) west of Boston. Consistently well-maintained at a fair price. Good choice if you want options.',
  },
  {
    name: 'Pinecrest Golf Club',
    slug: 'pinecrest',
    address: '256 Pinecrest Dr, Holliston, MA 01746',
    city: 'Holliston',
    lat: 42.2047, lng: -71.4249,
    phone: '(508) 429-9871',
    website: 'https://pinecrestgolfclub.org',
    golfnow_facility_id: '4520',
    golfnow_slug: 'pinecrest-golf-club',
    booking_provider: 'clubcaddie',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'Club Caddie booking engine landing; exact-date behavior needs browser verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 35, price_max: 52,
    quality_tier: 'public',
    characteristics: ['classic_layout', 'wooded', 'traditional'],
    description: 'Classic New England public course with a traditional wooded layout. Solid all-around option southwest of Boston.',
  },
  {
    name: 'Maplegate Country Club',
    slug: 'maplegate',
    address: '160 Maple St, Bellingham, MA 02019',
    city: 'Bellingham',
    lat: 42.0882, lng: -71.4740,
    phone: '(508) 966-4040',
    website: 'https://www.maplegate.com',
    golfnow_facility_id: '4521',
    golfnow_slug: 'maplegate-country-club',
    booking_provider: 'teeitup',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'Tee It Up booking engine supports course/date routing.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 40, price_max: 60,
    quality_tier: 'semi_private',
    characteristics: ['well_maintained', 'challenging', 'good_conditions'],
    description: 'Semi-private 18-hole course open to public. Well-manicured fairways and a genuinely challenging layout.',
  },
  {
    name: 'Butter Brook Golf Club',
    slug: 'butter-brook',
    address: '157 Goldsmith St, Westford, MA 01886',
    city: 'Westford',
    lat: 42.5800, lng: -71.4452,
    phone: '(978) 692-6560',
    website: 'https://www.butterbrookgc.com',
    golfnow_facility_id: '4522',
    golfnow_slug: 'butter-brook-golf-club',
    booking_provider: 'cps',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'CPS booking engine landing; may be bot-sensitive in automated browsers.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 38, price_max: 58,
    quality_tier: 'public',
    characteristics: ['good_value', 'well_maintained', 'northwest'],
    description: '18-hole public course northwest of Boston. Excellent conditioning for the price. Locals rate it highly.',
  },
  {
    name: 'Easton Country Club',
    slug: 'easton-cc',
    address: '265 Purchase St, South Easton, MA 02375',
    city: 'South Easton',
    lat: 42.0315, lng: -71.1174,
    phone: '(508) 238-2500',
    website: 'https://www.eastoncountryclub.com',
    golfnow_facility_id: '4523',
    golfnow_slug: 'easton-country-club',
    booking_provider: 'teequest',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'TeeQuest/course booking page; exact-date behavior needs browser verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 40, price_max: 60,
    quality_tier: 'public',
    characteristics: ['traditional', 'good_conditions'],
    description: 'Traditional 18-hole New England public course south of Boston. Good conditions and a proper layout.',
  },
  {
    name: 'New England Country Club',
    slug: 'new-england-cc',
    address: '180 Paine St, Bellingham, MA 02019',
    city: 'Bellingham',
    lat: 42.0775, lng: -71.4829,
    phone: '(508) 883-2300',
    website: 'https://www.newenglandcountryclub.com',
    golfnow_facility_id: '4524',
    golfnow_slug: 'new-england-country-club',
    booking_provider: 'teesnap',
    booking_capability: 'booking_engine_landing',
    booking_notes: 'TeeSnap booking engine landing; exact-date behavior needs browser verification.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$$', price_min: 55, price_max: 85,
    quality_tier: 'semi_private',
    characteristics: ['high_quality', 'championship_conditions', 'challenging', 'upscale'],
    description: 'Championship-caliber semi-private course open to the public. Best conditioning outside Granite Links. Good for serious players.',
  },
  {
    name: 'Foxborough Country Club',
    slug: 'foxborough-cc',
    address: '33 Walnut St, Foxborough, MA 02035',
    city: 'Foxborough',
    lat: 42.0668, lng: -71.2446,
    phone: '(508) 543-4661',
    website: 'https://www.foxboroughcc.com',
    golfnow_facility_id: '4525',
    golfnow_slug: 'foxborough-country-club',
    booking_provider: 'phone',
    booking_capability: 'phone_only',
    booking_notes: 'Public-play page directs users to course contact/manual booking.',
    holes_available: [18],
    walking_allowed: true,
    price_range: '$$', price_min: 42, price_max: 62,
    quality_tier: 'public',
    characteristics: ['challenging', 'elevation_changes', 'near_gillette'],
    description: '18-hole public course near Gillette Stadium. Interesting layout with elevation changes. More challenging than most public courses in the area.',
  },
]
